-- CHỈ CHẠY KHI CHƯA CÓ DB QL_KhachSan. Không chạy trên DB đang có dữ liệu.
CREATE DATABASE QL_KhachSan;
GO
USE QL_KhachSan;
GO

CREATE TABLE LOAIPHONG (
    MaLoai VARCHAR(10) NOT NULL,
    TenLoai NVARCHAR(50) NOT NULL,
    GiaCoBan DECIMAL(18, 2) NOT NULL,
    CONSTRAINT pk_LOAIPHONG PRIMARY KEY (MaLoai)
);

CREATE TABLE NHANVIEN (
    MaNV VARCHAR(10) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    VaiTro NVARCHAR(50) NOT NULL, 
    CONSTRAINT pk_NHANVIEN PRIMARY KEY (MaNV)
);

CREATE TABLE KHACHHANG (
    MaKH VARCHAR(10) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    Email VARCHAR(100),
    CCCD VARCHAR(20) NOT NULL,
    CONSTRAINT pk_KHACHHANG PRIMARY KEY (MaKH)
);

CREATE TABLE PHONG (
    MaPhong VARCHAR(10) NOT NULL,
    MaLoai VARCHAR(10) NOT NULL,
    SoPhong VARCHAR(10) NOT NULL,
    CONSTRAINT pk_PHONG PRIMARY KEY (MaPhong),
    CONSTRAINT fk_PHONG_LOAIPHONG FOREIGN KEY (MaLoai) REFERENCES LOAIPHONG(MaLoai)
);

CREATE TABLE DATPHONG (
    MaDatPhong VARCHAR(10) NOT NULL,
    MaKH VARCHAR(10) NOT NULL,
    MaNV VARCHAR(10) NOT NULL,
    TongTien DECIMAL(18, 2) NOT NULL,
    NgayTao DATETIME DEFAULT GETDATE(),
    TrangThai NVARCHAR(50) NOT NULL, 
    Version INT DEFAULT 1 NOT NULL,
    CONSTRAINT pk_DATPHONG PRIMARY KEY (MaDatPhong),
    CONSTRAINT fk_DATPHONG_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT fk_DATPHONG_NHANVIEN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE PHONG_NGAY (
    MaPhong VARCHAR(10) NOT NULL,
    Ngay DATE NOT NULL,
    MaDatPhong VARCHAR(10),
    CONSTRAINT pk_PHONG_NGAY PRIMARY KEY (MaPhong, Ngay),
    CONSTRAINT fk_PHONGNGAY_PHONG FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong),
    CONSTRAINT fk_PHONGNGAY_DATPHONG FOREIGN KEY (MaDatPhong) REFERENCES DATPHONG(MaDatPhong)
);

CREATE TABLE THANHTOAN (
    MaGD VARCHAR(30) NOT NULL,
    MaDatPhong VARCHAR(10) NOT NULL,
    SoTien DECIMAL(18, 2) NOT NULL,
    LoaiGiaoDich NVARCHAR(50) NOT NULL, 
    NgayGD DATETIME DEFAULT GETDATE(),
    CONSTRAINT pk_THANHTOAN PRIMARY KEY (MaGD),
    CONSTRAINT fk_THANHTOAN_DATPHONG FOREIGN KEY (MaDatPhong) REFERENCES DATPHONG(MaDatPhong)
);

CREATE TABLE DANHSACHCHO (
    MaWaitlist INT IDENTITY(1,1) NOT NULL, 
    MaKH VARCHAR(10) NOT NULL,
    MaLoai VARCHAR(10) NOT NULL,
    NgayMongMuon DATE NOT NULL,
    TrangThai NVARCHAR(50) DEFAULT N'Đang chờ', 
    CONSTRAINT pk_DANHSACHCHO PRIMARY KEY (MaWaitlist),
    CONSTRAINT fk_WAITLIST_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
    CONSTRAINT fk_WAITLIST_LOAIPHONG FOREIGN KEY (MaLoai) REFERENCES LOAIPHONG(MaLoai)
);
GO
USE QL_KhachSan;
GO
-- 1. Thêm Loại phòng
INSERT INTO LOAIPHONG (MaLoai, TenLoai, GiaCoBan) VALUES 
('STD', N'Standard', 500000),
('VIP', N'VIP', 1200000);

-- 2. Thêm Phòng vật lý
INSERT INTO PHONG (MaPhong, MaLoai, SoPhong) VALUES 
('P101', 'STD', '101'),
('P102', 'STD', '102'),
('V201', 'VIP', '201');

-- 3. Thêm Nhân viên
INSERT INTO NHANVIEN (MaNV, HoTen, VaiTro) VALUES 
('NV01', N'Lý Lễ Tân', N'Lễ tân'),
('NV02', N'Trần Quản Lý', N'Quản lý');

-- 4. Thêm Khách hàng
INSERT INTO KHACHHANG (MaKH, HoTen, SDT, Email, CCCD) VALUES 
('KH01', N'Nguyễn Văn An', '0901234567', 'an@email.com', '079123456789'),
('KH02', N'Phạm Thị Bình', '0912345678', 'binh@email.com', '079987654321');


INSERT INTO NHANVIEN (MaNV, HoTen, VaiTro) VALUES ('WEB', N'Hệ thống Website', N'Auto');

-- 5. Khởi tạo lưới Lịch phòng (PHONG_NGAY) cho 3 ngày (Chưa ai đặt -> MaDatPhong = NULL)
INSERT INTO PHONG_NGAY (MaPhong, Ngay, MaDatPhong) VALUES 
('P101', '2026-10-01', NULL), ('P101', '2026-10-02', NULL), ('P101', '2026-10-03', NULL),
('P102', '2026-10-01', NULL), ('P102', '2026-10-02', NULL), ('P102', '2026-10-03', NULL),
('V201', '2026-10-01', NULL), ('V201', '2026-10-02', NULL), ('V201', '2026-10-03', NULL);

-- 6. Tạo 1 Booking giả lập (Khách KH01 đặt phòng P101 trong 2 ngày 1/10 và 2/10)
INSERT INTO DATPHONG (MaDatPhong, MaKH, MaNV, TongTien, NgayTao, TrangThai, Version) VALUES 
('DP001', 'KH01', 'NV01', 1000000, GETDATE(), N'Đã đặt', 1);

-- Cập nhật Lịch phòng để chiếm chỗ cho Booking DP001
UPDATE PHONG_NGAY 
SET MaDatPhong = 'DP001' 
WHERE MaPhong = 'P101' AND Ngay IN ('2026-10-01', '2026-10-02');
GO
